# Generated by Django 4.0.1 on 2022-01-18 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Категория работы')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип работы')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.workcategory', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='Описание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.employee')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.worktype')),
            ],
        ),
    ]
